// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

import React from 'react';
// import ReactDebugMixin from 'react-debug-mixin';

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

var TermsOfService = React.createClass({
    // mixins: [ReactDebugMixin],
    render: function() {
        return (
            <div className="xxText">
                <h1 className="xxTitle">Privacy Policy</h1>
                <p>This Privacy Policy was last updated on June 30, 2013.</p>                
                
                <h1 className="xxCollection-title">Our Policy:</h1>
                <p>Welcome to the web site (the &ldquo;Site&rdquo;) of Neon Labs, Inc. (&ldquo;Neon Labs&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo; and/or &ldquo;our&rdquo;). This Site is operated by Neon Labs and has been created to provide information about our company and our thumbnail optimization and video analytics service (together with the Site, the &ldquo;Services&rdquo;) to our Service visitors (&ldquo;you&rdquo;, &ldquo;your&rdquo;). This Privacy Policy sets forth Neon Labs&rsquo;s policy with respect to information including personally identifiable data (&ldquo;Personal Data&rdquo;) and other information that is collected from visitors to the Site and Services.</p>                
                <h1 className="xxCollection-title">Information We Collect:</h1>
                <p><b>When you interact with us through the Services, we may collect Personal Data and other information from you, as further described below:</b></p>
                <p><strong>Personal Data That You Provide Through the Services:</strong></p> 
                <p>We collect Personal Data from you when you voluntarily provide such information, such as when you contact us with inquiries, respond to one of our surveys, register for access to the Services or use certain Services. Wherever Neon Labs collects Personal Data we make an effort to provide a link to this Privacy Policy.</p>
                <p><strong>By voluntarily providing us with Personal Data, you are consenting to our use of it in accordance with this Privacy Policy. If you provide Personal Data to the Services, you acknowledge and agree that such Personal Data may be transferred from your current location to the offices and servers of Neon Labs and the authorized third parties referred to herein located in the United States.</strong></p>

                <h1 className="xxCollection-title">Other Information:</h1>
                <h1 className="xxPage-Subtitle">Non-Identifiable Data:</h1>
                <p>When you interact with Neon Labs through the Services, we receive and store certain personally non-identifiable information. Such information, which is collected passively using various technologies, cannot presently be used to specifically identify you. Neon Labs may store such information itself or such information may be included in databases owned and maintained by Neon Labs affiliates, agents or service providers. The Services may use such information and pool it with other information to track, for example, the total number of visitors to our Site, the number of visitors to each page of our Site, and the domain names of our visitors' Internet service providers. It is important to note that no Personal Data is available or used in this process.</p>
                <p>In operating the Services, we may use a technology called "cookies." A cookie is a piece of information that the computer that hosts our Services gives to your browser when you access the Services. Our cookies help provide additional functionality to the Services and help us analyze Services usage more accurately. For instance, our Services may set a cookie on your browser that allows you to access the Services without needing to remember and then enter a password more than once during a visit to the Services. In all cases in which we use cookies, we will not collect Personal Data except with your permission. On most web browsers, you will find a &ldquo;help&rdquo; section on the toolbar. Please refer to this section for information on how to receive notification when you are receiving a new cookie and how to turn cookies off. We recommend that you leave cookies turned on because they allow you to take advantage of some of the Service features.</p>
                <h1 className="xxPage-Subtitle">Aggregated Personal Data:</h1> 
                <p>In an ongoing effort to better understand and serve the users of the Services, Neon Labs often conducts research on its customer demographics, interests and behavior based on the Personal Data and other information provided to us. This research may be compiled and analyzed on an aggregate basis, and Neon Labs may share this aggregate data with its affiliates, agents and business partners. This aggregate information does not identify you personally. Neon Labs may also disclose aggregated user statistics in order to describe our services to current and prospective business partners, and to other third parties for other lawful purposes.</p>

                <h1 className="xxCollection-title">Our Use of Your Personal Data and Other Information:</h1>
                <p>Neon Labs uses the Personal Data you provide in a manner that is consistent with this Privacy Policy. If you provide Personal Data for a certain reason, we may use the Personal Data in connection with the reason for which it was provided. For instance, if you contact us by email, we will use the Personal Data you provide to answer your question or resolve your problem. Also, if you provide Personal Data in order to obtain access to the Services, we will use your Personal Data to provide you with access to such services and to monitor your use of such services. Neon Labs and its subsidiaries and affiliates (the &ldquo;Neon Labs Related Companies&rdquo;) may also use your Personal Data and other personally non-identifiable information collected through the Services to help us improve the content and functionality of the Services, to better understand our users and to improve the Services. Neon Labs and its affiliates may use this information to contact you in the future to tell you about services we believe will be of interest to you. If we do so, each marketing communication we send you will contain instructions permitting you to "opt-out" of receiving future marketing communications. In addition, if at any time you wish not to receive any future marketing communications or you wish to have your name deleted from our mailing lists, please contact us as indicated below.</p>
                <p>If Neon Labs intends on using any Personal Data in any manner that is not consistent with this Privacy Policy, you will be informed of such anticipated use prior to or at the time at which the Personal Data is collected.</p>
                    
                <h1 className="xxCollection-title">Our Disclosure of Your Personal Data and Other Information:</h1>
                <p>Neon Labs is not in the business of selling your information. We consider this information to be a vital part of our relationship with you. There are, however, certain circumstances in which we may share your Personal Data with certain third parties without further notice to you, as set forth below:</p>
                <p><strong>Business Transfers:</strong> As we develop our business, we might sell or buy businesses or assets. In the event of a corporate sale, merger, reorganization, dissolution or similar event, Personal Data may be part of the transferred assets.</p>
                <p><strong>Related Companies:</strong> We may also share your Personal Data with our Related Companies for purposes consistent with this Privacy Policy.</p>
                <p><strong>Agents, Consultants and Related Third Parties:</strong> Neon Labs, like many businesses, sometimes hires other companies to perform certain business-related functions. Examples of such functions include mailing information, maintaining databases and processing payments. When we employ another entity to perform a function of this nature, we only provide them with the information that they need to perform their specific function.</p>
                <p><strong>Legal Requirements:</strong> Neon Labs may disclose your Personal Data if required to do so by law or in the good faith belief that such action is necessary to (i) comply with a legal obligation, (ii) protect and defend the rights or property of Neon Labs, (iii) act in urgent circumstances to protect the personal safety of users of the Services or the public, or (iv) protect against legal liability.</p>
                    
                <h1 className="xxCollection-title">Your Choices:</h1>
                <p>You can visit the Site without providing any Personal Data. If you choose not to provide any Personal Data, you may not be able to use certain Services.</p>
                    
                <h1 className="xxCollection-title">Exclusions:</h1>
                <p>This Privacy Policy does not apply to any Personal Data collected by Neon Labs other than Personal Data collected through the Services. This Privacy Policy shall not apply to any unsolicited information you provide to Neon Labs through the Services or through any other means. This includes, but is not limited to, information posted to any public areas of the Services, such as forums, any ideas for new products or modifications to existing products, and other unsolicited submissions (collectively, &ldquo;Unsolicited Information&rdquo;). All Unsolicited Information shall be deemed to be non-confidential and Neon Labs shall be free to reproduce, use, disclose, and distribute such Unsolicited Information to others without limitation or attribution.</p>
                
                <h1 className="xxCollection-title">Children:</h1>
                <p>Neon Labs does not knowingly collect Personal Data from children under the age of 13. If you are under the age of 13, please do not submit any Personal Data through the Services. We encourage parents and legal guardians to monitor their children&rsquo;s Internet usage and to help enforce our Privacy Policy by instructing their children never to provide Personal Data on the Services without their permission. If you have reason to believe that a child under the age of 13 has provided Personal Data to Neon Labs through the Services, please contact us, and we will endeavor to delete that information from our databases.</p>
                    
                <h1 className="xxCollection-title">Links to Other Web Sites:</h1>
                <p>This Privacy Policy applies only to the Services. The Services may contain links to other web sites not operated or controlled by Neon Labs (the &ldquo;Third Party Sites&rdquo;). The policies and procedures we described here do not apply to the Third Party Sites. The links from the Services do not imply that Neon Labs endorses or has reviewed the Third Party Sites. We suggest contacting those sites directly for information on their privacy policies.</p>
                    
                <h1 className="xxCollection-title">Security:</h1>
                <p>Neon Labs takes reasonable steps to protect the Personal Data provided via the Services from loss, misuse, and unauthorized access, disclosure, alteration, or destruction. However, no Internet or email transmission is ever fully secure or error free. In particular, email sent to or from the Services may not be secure. Therefore, you should take special care in deciding what information you send to us via email. Please keep this in mind when disclosing any Personal Data to Neon Labs via the Internet.</p>
                    
                <h1 className="xxCollection-title">Other Terms and Conditions:</h1>
                <p>Your access to and use of the Services is subject to the Terms of Service at www.neon-lab.com/terms.</p>
                    
                <h1 className="xxCollection-title">Changes to Neon Labs&rsquo;s Privacy Policy:</h1>
                <p>The Services and our business may change from time to time. As a result, at times it may be necessary for Neon Labs to make changes to this Privacy Policy. Neon Labs reserves the right to update or modify this Privacy Policy at any time and from time to time without prior notice. Please review this policy periodically, and especially before you provide any Personal Data. This Privacy Policy was last updated on the date indicated above. Your continued use of the Services after any changes or revisions to this Privacy Policy shall indicate your agreement with the terms of such revised Privacy Policy.</p>
                    
                <h1 className="xxCollection-title">Access to Information; Contacting Neon Labs:</h1>
                <p>To keep your Personal Data accurate, current, and complete, please contact us as specified below. We will take reasonable steps to update or correct Personal Data in our possession that you have previously submitted via the Services.</p>
                <p>Please also feel free to contact us if you have any questions about Neon Labs&rsquo;s Privacy Policy or the information practices of the Services.</p>
                <p>You may contact us as follows: ask@neon-lab.com</p>



                <h1 className="xxTitle">Terms of Service</h1>

                <h1 className="xxCollection-title">Acceptance of Terms.</h1>
                <p>Neon Labs, Inc. (&ldquo;Neon Labs&rdquo;) provides its Service (as defined below) and its web site located at http://www.neon- lab.com (the &ldquo;Site&rdquo;), subject to this Terms of Service agreement (&ldquo;TOS&rdquo;). By accepting this TOS or by accessing or using the Service or Site, you acknowledge that you have read, understood, and agree to be bound by this TOS. If you are entering into this TOS on behalf of a company, business or other legal entity, you represent that you have the authority to bind such entity and its affiliates to this TOS, in which case the terms &ldquo;you&rdquo; or &ldquo;your&rdquo; shall refer to such entity and its affiliates. If you do not have such authority, or if you do not agree with this TOS, you must not accept this TOS and may not use the Service.</p>
                <p>Neon Labs reserves the right, at its sole discretion, to change or modify portions of these TOS at any time. Neon Labs will post changes on this page and will indicate at the top of this page the date these terms were last revised. Neon Labs will also use commercially reasonable efforts to notify you of changes, either through the Services user interface, in an email notification, or other means. Any such changes will become effective no earlier than fourteen (14) days after they are posted, except that changes addressing new functions of the Services or changes made for legal reasons will be effective immediately. Your continued use of the Service after the date any such changes become effective constitutes your acceptance of the new TOS.</p>
                <h1 className="xxPage-Subtitle">Description of Service.</h1> 
                <p>The &ldquo;Service&rdquo; includes (a) the Site, (b) Neon Labs&rsquo;s thumbnail optimization and video analytics services, and (c) any software (including the Software, as defined below), data, reports, text, images, sounds, video, and content made available through any of the foregoing (collectively referred to as the &ldquo;Content&rdquo;). Any new features added to or augmenting the Service are also subject to this TOS.</p>
                <h1 className="xxPage-Subtitle">General Conditions/ Access and Use of the Service.</h1>
                <p>Subject to the terms and conditions of this TOS, you may access and use the Service only for lawful purposes. All rights, title and interest in and to the Service and its components (excluding Your Content, as defined below) will remain with and belong exclusively to Neon Labs. You shall not (a) sublicense, resell, rent, lease, transfer, assign, time share or otherwise commercially exploit or make the Service available to any third party; (b) use the Service in any unlawful manner (including without limitation in violation of any data, privacy or export control laws) or in any manner that interferes with or disrupts the integrity or performance of the Service or its components, or (c) modify, adapt or hack the Service to, or otherwise attempt to gain unauthorized access to the Service or its related systems or networks. You shall comply with any codes of conduct, policies or other notices Neon Labs provides you or publishes in connection with the Service, and you shall promptly notify Neon Labs if you learn of a security breach related to the Service.</p>
                <p>Any software that may be made available by Neon Labs in connection with the Service (&ldquo;Software&rdquo;) contains proprietary and confidential information that is protected by applicable intellectual property and other laws. Subject to the terms and conditions of this TOS, Neon Labs hereby grants you a personal, non-transferable, non- sublicensable and non-exclusive right and license to use the object code of any Software solely in connection with the Service, provided that you shall not (and shall not allow any third party to) copy, modify, create a derivative work of, reverse engineer, reverse assemble or otherwise attempt to discover any source code or sell, assign, sublicense or otherwise transfer any right in any Software. You agree not to access the Service by any means other than through the interface that is provided by Neon Labs for use in accessing the Service. Any rights not expressly granted herein are reserved and no license or right to use any trademark of Neon Labs or any third party is granted to you in connection with the Service.</p>
                <p>You are solely responsible for all videos, data, information, feedback, suggestions, text, content and other materials that you upload, post, deliver, provide or otherwise transmit or store (hereafter &ldquo;transmit(ting)&rdquo;) in connection with or relating to the Service (&ldquo;Your Content&rdquo;). You are responsible for maintaining the confidentiality of your login, password and account and for all activities that occur under your login or account. All rights, title and interest in and to Your Content will remain with and belong exclusively to you. By transmitting Your Content on or through the Service, You hereby do and shall grant Neon Labs a worldwide, non-exclusive, royalty-free, sublicensable and transferable license to use Your Content to provide you the Service. Neon Labs shall have the right to collect and analyze data and other information relating to the use and performance of various aspects of the Service and related systems and technologies, and Neon Labs will be free to (i) use such information and data (during and after the term hereof) to improve and enhance the Service and for other development, diagnostic and corrective purposes in connection with the Services and other Neon Labs offerings, and (ii) disclose such data in aggregate or other de-identified form in connection with its business. Neon Labs reserves the right to remove or disable any Content that violates these TOS (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such Content).</p>
                <p> You understand that the operation of the Service, including Your Content, may be unencrypted and involve (a) transmissions over various networks; (b) changes to conform and adapt to technical requirements of connecting networks or devices and (c) transmission to Neon Labs&rsquo;s third party vendors and hosting partners to provide the necessary hardware, software, networking, storage, and related technology required to operate and maintain the Service. Accordingly, you acknowledge that you bear sole responsibility for adequate security, protection and backup of Your Content. Neon Labs will have no liability to you for any unauthorized access or use of any of Your Content, or any corruption, deletion, destruction or loss of any of Your Content.</p>
                <p>The failure of Neon Labs to exercise or enforce any right or provision of this TOS shall not be a waiver of that right. You acknowledge that this TOS is a contract between you and Neon Labs, even though it is electronic and is not physically signed by you and Neon Labs, and it governs your use of the Service and takes the place of any prior agreements between you and Neon Labs.</p>
                <h1 className="xxPage-Subtitle">Payment.</h1> 
                <p>To the extent the Service or any portion thereof is made available for any fee, you will be required to select a payment plan and provide Neon Labs information regarding your credit card or other payment instrument. You represent and warrant to Neon Labs that such information is true and that you are authorized to use the payment instrument. You will promptly update your account information with any changes (for example, a change in your billing address or credit card expiration date) that may occur. You agree to pay Neon Labs the amount that is specified in the payment plan in accordance with the terms of such plan and this TOS. You hereby authorize Neon Labs to bill your payment instrument in advance on a periodic basis in accordance with the terms of the applicable payment plan until you terminate your account, and you further agree to pay any charges so incurred. If you dispute any charges you must let Neon Labs know within sixty (60) days after the date that Neon Labs invoices you. We reserve the right to change Neon Labs&rsquo;s prices. If Neon Labs does, Neon Labs will provide notice of the change on the Site or in email to you, at Neon Labs&rsquo;s option, at least 30 days before the change is to take effect. Your continued use of the Service after the price change becomes effective constitutes your agreement to pay the changed amount.</p>
                <h1 className="xxPage-Subtitle">Representations and Warranties.</h1> 
                <p>You represent and warrant to Neon Labs that (i) you have full power and authority to enter into this TOS; (ii) you own all Your Content or have obtained all permissions, releases, rights or licenses required to engage in your uploading or transmitting of Content and other activities (and allow Neon Labs to perform its obligations) in connection with the Services without obtaining any further releases or consents; (iii) Your Content and other activities in connection with the Service, and Neon Labs&rsquo;s exercise of all rights and license granted by you herein, do not and will not violate, infringe, or misappropriate any third party&rsquo;s copyright, trademark, right of privacy or publicity, or other personal or proprietary right, nor does Your Content contain any matter that is defamatory, obscene, unlawful, threatening, abusive, tortious, offensive or harassing; and (iv) you are eighteen (18) years of age or older.</p>
                <h1 className="xxPage-Subtitle">Termination.</h1>
                <p>You have the right to terminate your account at any time in accordance with the procedures set forth on the Site. Neon Labs reserves the right to (i) modify or discontinue, temporarily or permanently, the Service (or any part thereof) and (ii) refuse any and all current and future use of the Service, suspend or terminate your account (any part thereof) or use of the Service and remove and discard any of Your Content in the Service if you violate this TOS. Neon Labs shall not be liable to you or any third party for any modification, suspension or discontinuation of the Service. Neon Labs will use good faith efforts to contact you to warn you prior to suspension or termination of your account by Neon Labs. If Neon Labs terminates your account without cause and you have signed up for a fee-bearing service, Neon Labs will refund the pro-rated, unearned portion of any amount that you have prepaid to Neon Labs for such Service. All accrued rights to payment and the terms of Section 4-12 shall survive termination of this TOS.</p>
                <h1 className="xxPage-Subtitle">DISCLAIMER OF WARRANTIES.</h1>
                <p>THE SERVICE, INCLUDING THE SITE AND CONTENT, AND ALL SERVER AND NETWORK COMPONENTS ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS WITHOUT ANY WARRANTIES OF ANY KIND, AND NEON LABS EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. YOU ACKNOWLEDGE THAT NEON LABS DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, ERROR-FREE OR VIRUS-FREE AND NO INFORMATION, ADVICE OR SERVICES OBTAINED BY YOU FROM NEON LABS OR THROUGH THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THIS TOS.</p>
                <h1 className="xxPage-Subtitle">LIMITATION OF LIABILITY.</h1>
                <p>UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (WHETHER IN CONTRACT, TORT, OR OTHERWISE) SHALL NEON LABS BE LIABLE TO YOU OR ANY THIRD PARTY FOR (A) ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, LOST SALES OR BUSINESS, LOST DATA OR BUSINESS INTERRUPTION, OR (B) FOR ANY DIRECT DAMAGES, COSTS, LOSSES OR LIABILITIES IN EXCESS OF THE FEES ACTUALLY PAID BY YOU IN THE SIX (6) MONTHS PRECEDING THE EVENT GIVING RISE TO YOUR CLAIM OR, IF NO FEES APPLY, ONE HUNDRED ($100) U.S. DOLLARS. THE PROVISIONS OF THIS SECTION ALLOCATE THE RISKS UNDER THIS TOS BETWEEN THE PARTIES, AND THE PARTIES HAVE RELIED ON THESE LIMITATIONS IN DETERMINING WHETHER TO ENTER INTO THIS TOS.</p>
                <p>Some states do not allow the exclusion of implied warranties or limitation of liability for incidental or consequential damages, which means that some of the above limitations may not apply to you. IN THESE STATES, NEON LAB&rsquo;S LIABILITY WILL BE LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW.</p>
                <h1 className="xxPage-Subtitle">Indemnification.</h1>
                <p>You shall defend, indemnify, and hold harmless Neon Labs from and against any claims, actions or demands, including without limitation reasonable legal and accounting fees, arising or resulting from your breach of this TOS, any of Your Content, or your other access, contribution to, use or misuse of the Service. Neon Labs shall provide notice to you of any such claim, suit or demand. Neon Labs reserves the right to assume the exclusive defense and control of any matter which is subject to indemnification under this section. In such case, you agree to cooperate with any reasonable requests assisting Neon Labs&rsquo;s defense of such matter.</p>
                <h1 className="xxPage-Subtitle">Assignment.</h1> 
                <p>You may not assign this TOS without the prior written consent of Neon Labs, but Neon Labs may assign or transfer this TOS, in whole or in part, without restriction.</p>
                <h1 className="xxPage-Subtitle">Governing Law.</h1>
                <p>This TOS shall be governed by the laws of the State of California without regard to the principles of conflicts of law. Unless otherwise elected by Neon Labs in a particular instance, you hereby expressly agree to submit to the exclusive personal jurisdiction of the federal and state courts of the State of California for the purpose of resolving any dispute relating to your access to or use of the Service.</p>
                <h1 className="xxPage-Subtitle">Privacy.</h1> 
                <p>Please visit our Privacy Policy to understand how Neon Labs collects and uses personal information.DMCA The Digital Millennium Copyright Act of 1998 (the &ldquo;DMCA&rdquo;) provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. Neon Labs will promptly process and investigate notices of alleged infringement and will take appropriate actions under the DMCA and other applicable intellectual property laws with respect to any alleged or actual infringement. A notification of claimed copyright infringement should be emailed to Neon Labs&rsquo;s Copyright Agent at copyright@neon-lab.com (subject line: &ldquo;DMCA&rdquo; Takedown Request&rdquo;). You may also contact us by mail or facsimile at:</p>
                    <blockquote>
                        Attention: Copyright Agent<br></br>
                        Neon Labs, Inc.<br></br>
                        156 2nd Street <br></br>
                        San Francisco, CA 94105
                    </blockquote>
                <h1 className="xxPage-Subtitle">Notice:</h1>
                <p>To be effective, the notification must be in writing and contain the following information:</p>
                <p><ul className="ul-disc">
                    <li> An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest;</li>
                    <li> A description of the copyrighted work or other intellectual property that you claim has been infringed;</li>
                    <li> A description of where the material that you claim is infringing is located on the Site, with enough detail that we may find it on the Site;</li>
                    <li> Your address, telephone number, and email address;</li>
                    <li> A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright or intellectual property owner, its agent, or the law;</li>
                    <li> A statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner‘s behalf.</li>
                </ul></p>
                <h1 className="xxPage-Subtitle">Counter-Notice: </h1> 
                <p>If you believe that the relevant Content that was removed (or to which access was disabled) is not infringing, or that you have the authorization from the copyright owner, the copyright owner&rsquo;s agent, or pursuant to the law, to post and use such Content, you may send a written counter-notice containing the following information to the Copyright Agent:</p>
                <p><ul className="ul-disc">
                    <li>Your physical or electronic signature;</li>
                    <li>Identification of the content that has been removed or to which access has been disabled and the location at which the content appeared before it was removed or disabled;</li>
                    <li>A statement that you have a good faith belief that the content was removed or disabled as a result of mistake or a misidentification of the content;</li> 
                    <li>Your name, address, telephone number, and e-mail address, a statement that you consent to the jurisdiction of the federal court located within the Northern District of California and a statement that you will accept service of process from the person who provided notification of the alleged infringement.</li>
                </ul></p>
                <p>If a counter-notice is received by the Copyright Agent, Neon Labs will send a copy of the counter-notice to the original complaining party informing that person that it may replace the removed content or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the content provider, member or user, the removed content may be replaced, or access to it restored, in 10 to 14 business days or more after receipt of the counter-notice, at Neon Labs&rsquo;s sole discretion.</p>
                <h1 className="xxPage-Subtitle">Repeat Infringer Policy:</h1> 
                <p>In accordance with the DMCA and other applicable law, Neon Labs has adopted a policy of terminating, in appropriate circumstances and at Neon Labs's sole discretion, members who are deemed to be repeat infringers. Neon Labs may also at its sole discretion limit access to the Site and/or terminate the memberships of any users who infringe any intellectual property rights of others, whether or not there is any repeat infringement.</p>
            </div>
        )
    }
})
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export default TermsOfService;

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
